name: 'Setup Python Environment'
description: 'Install uv and project dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.15"

    - name: Install the project
      run: uv sync --locked --dev
      shell: bash
