name: MNIST Server Pipeline

on: [push]

jobs:
   static-analysis:
     name: Static Analysis
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v5
       - name: Setup Python environment
         uses: ./.github/actions/setup-python-env
       - name: Ruff Check
         run: uv run ruff check

   unit-test:
     name: Unit Test
     runs-on: ubuntu-latest
     strategy:
       matrix:
         package: [model, backend]
     steps:
       - uses: actions/checkout@v5
       - name: Setup Python environment
         uses: ./.github/actions/setup-python-env
       - name: Test ${{ matrix.package }}
         working-directory: ${{ matrix.package }}
         run: uv run pytest
