name: MNIST Server Pipeline

on: [push]

jobs:
   static-analysis:
     name: Static Analysis
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v5
       - name: Setup Python environment
         uses: ./.github/actions/setup-python-env
       - name: Ruff Check
         run: uv run ruff check

   unit-test:
     name: Unit Test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v5
       - name: Model Test
         run: cd model
       - name: Setup Python environment
         uses: ./.github/actions/setup-python-env
       - name: Run tests
         run: uv run pytest
       - name: Backend Test
         run: cd ../backend
       - name: Setup Python environment
         uses: ./.github/actions/setup-python-env
       - name: Run tests
         run: uv run pytest
