name: MNIST Server Pipeline

on: [push]
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.15"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Ruff Check
        run: uv run ruff check
